### ISSUE TITLE
Dev content review 1

### ISSUE THREAD

**Issue by gkwan-ibm** [k-rtik/draft-guide-sl#1]
- [x] Social Login -> Social Media Login
- [x] remove `:page-guide-category: microprofile` from the README.adoc
- [x] the short descriptions the site and guide, change "REST service" to "RESTful web service"
- **What you’ll learn**
  - [x] "REST service" to "RESTful web service"
  - [x] remove "and test" because I think we do not really test all those different logins
  - [x] SocialLogin -> Social Media Login feature
  - [x] Create a link on "Social Media Login feature" to https://openliberty.io/docs/ref/feature/#socialLogin-1.0.html
  - [x] Reword the first paragraph to be better. In my opinion, it is not clear
  - [x] May explain why need social login and its advantages at the beginning
  - [x] the following statement is weak. Either remove it or give a better reason.
    - "This feature allows you to easily secure your service"
- [x] Missing **Getting started** section
- [x] I don't think we need **Try what you’ll build** sub section
- **Prerequisites**
  - [x] Move the **Prerequisites** sub-section to be a main section and rename to **Setting up the certifiates and trust store**
  - [x] "can run/build" -> "build"
  - [x] Say somethink like "use Firefox as an example"
  - [x] Are there any specific URLs for those websites? If I have no account for those websites, how can I get the certificates?
  - [x] use the word "truststore" or "trust store" consistently across the guide
  - [x] "As part of the guide,  you will be configuring" -> "Configure"
- **Securing the JAX-RS service**
  - [x] the content is not clear
    - is it easier to ask readers to update the server.xml once, then explain the detail one by one?
  - [x] why there are Server.xml and server.xml
  - [x] format the server.xml and HelloService.java better, no wrapped lines
  - [x] no need to show the license comments for the HelloService.java (i.e. hide license comments)
- **Adding social media login configurations**
  - [x] No update/replace instucture, may be combine with the above section 
- [x] suggest to reorg the sections and subsections as following:
  - suggest following:
    - **Securing Hello Service**
      - update HelloService.java and explain the details
    - **Configuring the security and socal media login**
      - Configuring the security roles
      - Adding required features
      - Adding keystores
      - Adding Github login configuration
      - Adding Amazon login configuration
      - Adding Google login configuration
- **Building and running the application**
  - [x] ask readers to try to login in either account and show what the output will look like
- **Testing the service**
  - [x] format the EndpointIT.java with no wrapped lines
  - [x] I don't think we need the detail to explain the whole test because the test is not really test the login. Make it simple: create the file and run the test

**Comment by k-rtik** [comment]
Repo moved to: https://github.com/OpenLiberty/draft-guide-social-login/

[Second content review](https://github.com/OpenLiberty/draft-guide-social-login/issues/1)
